modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"

[[mods]]
modId="turtlelib"
version="${file.jarVersion}"
displayName="${turtlelib_name}"
displayURL="https://github.com/hrobasti/turtle-lib-mod"
logoFile="icon.png"
authors="hrobasti"
description='''
Shared helper library for Fabric/NeoForge mods.
Source: https://github.com/hrobasti/turtle-lib-mod
GitHub Sponsors: https://github.com/sponsors/hrobasti
Ko-Fi: https://ko-fi.com/hrobasti
'''

[[dependencies.turtlelib]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.turtlelib]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
